### ISSUE TITLE
how to, documentation or install.md?

### ISSUE THREAD

**Issue by joubertredrat** [mangelajo/ovh-ebtables-agent#1]
Hi,

I'm trying to use this agent but I not found documentation, is possible to share documentation with we?

Thanks

**Comment by xelfe** [comment]
Same here, I would like to know how to apply this please. Nice solution for ovh setup is not very popular so please, show us the white rabbit !

**Comment by mangelajo** [comment]
Hi, I updated the files after the Mar 26th comment, and talked to redrat on IRC, 

I'll try to put some install instructions together.

**Comment by xelfe** [comment]
Cool. It's so hard to manage a openstack setup on ovh server. I can't wait to try your solution ! Is it that simple that type ex; python setup.py install ?!

**Comment by joubertredrat** [comment]
@xelfe for lack of time  I had to use the Proxmox.

Openstack runs very fine on SoYouStart Servers, I used RDO to install, compute and storage works very fine, the problem is only networking.

@mangelajo, sorry, you helped me, but I really had no time to try again, but in future I will try to get another SYS server to try again.

**Comment by robputt** [comment]
Hi mangelajo,

I am really eager to give this a try... Can you provide some basic install instructions? Even if it's just a oneliner...

Regards,

Rob

**Comment by xelfe** [comment]
I think we only have to clone the repo and do; python setup.py install

Is that right @mangelajo ?

**Comment by mangelajo** [comment]
@xelfe, it's more than that.

You have to put a bridge in front of eth: https://github.com/mangelajo/ovh-ebtables-agent/blob/master/bin/ovh-bridge-eth

to do the ebtables manipulation.

Also, you need to setup a single virtual mac for all your IPs in the OVH apis, and then edit this agent config file to handle that...

**Comment by BinSlashBash** [comment]
@xelfe you could install?

**Comment by joubertredrat** [comment]
Hi guys,

Always when I try to run this script I lost my connection with server, then I need to reinstall OS. Have another way to run script?

**Comment by joubertredrat** [comment]
@xelfe you could install?

**Comment by nicosmuts** [comment]
@mangelajo could you please provide some guidance on running this? I am really keen to build OpenStack on OVH, but the networking remains an issue.

**Comment by joubertredrat** [comment]
@nicosmuts you could install on OVH?
